SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[Console_GetPrevDealer]
(@DealerID varchar(10))
AS
BEGIN

SET NOCOUNT ON;

DECLARE @N1 INT
DECLARE @N2 VARCHAR(10)

CREATE TABLE #t1
(
ID INT IDENTITY(1,1) PRIMARY KEY,
DEALERID VARCHAR(10)
);

INSERT INTO #T1(DealerID)
SELECT DISTINCT DealerID FROM testDealer;
SET @N1 = (SELECT ID FROM #t1 WHERE DealerID = @DealerID);
SET @N2 = (Select DealerID FROM #t1 WHERE ID = @N1- 1)
SELECT @N2
DROP TABLE #t1;
END;
GO
